export const COMMON_FACILITY_ISSUES = [
  "Broken Ceiling Fan",
  "Broken Lights",
  "Broken Door",
  "Broken Window",
  "Broken Chair",
  "Broken Table",
  "Broken Whiteboard",
  "Broken Projector",
  "Broken Air Conditioning",
  "Leaking Faucet",
  "Clogged Toilet",
  "Damaged Flooring",
  "Damaged Ceiling",
  "Broken Electrical Outlet",
  "Pest Infestation",
  "Water Damage",
  "Mold Growth",
  "Broken Lock",
  "Graffiti/Vandalism",
  "Poor Ventilation",
] as const;
