export const COMMON_FACILITY_REPORTS = [
  { value: "broken_ceiling_fan", label: "Broken Ceiling Fan" },
  { value: "broken_lights", label: "Broken Lights" },
  { value: "broken_ac", label: "Broken Air Conditioner" },
  { value: "broken-whiteboard", label: "Broken Whiteboard" },
  { value: "broken-projector", label: "Broken Projector" },
  { value: "broken_window", label: "Broken Window" },
  { value: "broken_door", label: "Broken Door" },
  { value: "broken_chair", label: "Broken Chair" },
  { value: "broken_desk", label: "Broken Desk" },
  { value: "broken_computer", label: "Broken Computer" },
  { value: "leaking-faucet", label: "Leaking Faucet" },
  { value: "clogged-toilet", label: "Clogged Toilet" },
  { value: "damaged-flooring", label: "Damaged Flooring" },
  { value: "water-damage", label: "Water Damage" },
  { value: "broken-lock", label: "Broken Lock" },
  { value: "graffiti-vandalism", label: "Graffiti/Vandalism" },
  { value: "poor-ventilation", label: "Poor Ventilation" },
];
