CREATE INDEX `user_role_is_active_idx` ON `user` (`role`,`is_active`);--> statement-breakpoint
CREATE INDEX `user_dept_idx` ON `user` (`department_or_organization`);--> statement-breakpoint
CREATE INDEX `borrowing_classroom_date_idx` ON `classroom_borrowing` (`classroom_id`,`date`);--> statement-breakpoint
CREATE INDEX `borrowing_faculty_date_idx` ON `classroom_borrowing` (`faculty_id`,`date`);--> statement-breakpoint
CREATE INDEX `schedule_classroom_day_idx` ON `classroom_schedule` (`classroom_id`,`day`);--> statement-breakpoint
CREATE INDEX `schedule_faculty_day_idx` ON `classroom_schedule` (`faculty_id`,`day`);--> statement-breakpoint
CREATE INDEX `vacancy_classroom_date_idx` ON `classroom_vacancy` (`classroom_id`,`date`);--> statement-breakpoint
CREATE INDEX `room_req_classroom_idx` ON `room_requests` (`classroom_id`);--> statement-breakpoint
CREATE INDEX `room_req_requester_idx` ON `room_requests` (`requester_id`);--> statement-breakpoint
CREATE INDEX `room_req_responder_status_date_idx` ON `room_requests` (`responder_id`,`status`,`date`);--> statement-breakpoint
CREATE INDEX `room_req_date_idx` ON `room_requests` (`date`);--> statement-breakpoint
CREATE INDEX `classroom_building_idx` ON `classroom` (`building_id`);--> statement-breakpoint
CREATE INDEX `classroom_type_idx` ON `classroom` (`type`);--> statement-breakpoint
CREATE INDEX `report_reported_by_idx` ON `facility_issue_report` (`reported_by`);--> statement-breakpoint
CREATE INDEX `report_category_idx` ON `facility_issue_report` (`category`);--> statement-breakpoint
CREATE INDEX `report_status_idx` ON `facility_issue_report` (`status`);--> statement-breakpoint
CREATE INDEX `report_date_reported_idx` ON `facility_issue_report` (`date_reported`);--> statement-breakpoint
CREATE INDEX `report_building_idx` ON `facility_issue_report` (`building_id`);--> statement-breakpoint
CREATE INDEX `report_classroom_idx` ON `facility_issue_report` (`classroom_id`);--> statement-breakpoint
CREATE INDEX `borrow_trans_borrower_idx` ON `borrowing_transaction` (`borrower_id`);--> statement-breakpoint
CREATE INDEX `borrow_trans_status_date_idx` ON `borrowing_transaction` (`status`,`date_borrowed`);--> statement-breakpoint
CREATE INDEX `borrow_trans_venue_res_idx` ON `borrowing_transaction` (`venue_reservation_id`);--> statement-breakpoint
CREATE INDEX `res_borrow_transaction_idx` ON `resource_borrowing` (`transaction_id`);--> statement-breakpoint
CREATE INDEX `res_borrow_resource_idx` ON `resource_borrowing` (`resource_id`);--> statement-breakpoint
CREATE INDEX `venue_res_venue_idx` ON `venue_reservation` (`venue_id`);--> statement-breakpoint
CREATE INDEX `venue_res_reserver_idx` ON `venue_reservation` (`reserver_id`);--> statement-breakpoint
CREATE INDEX `venue_res_status_date_idx` ON `venue_reservation` (`status`,`date`);--> statement-breakpoint
CREATE INDEX `venue_res_date_idx` ON `venue_reservation` (`date`);